In [5]:
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [1]:
# Define the file path to the historical dataset
file_path = "data/seoul_air_1988_2021.csv"

# Load the CSV file into a pandas DataFrame
print("Loading dataset...")
df = pd.read_csv(file_path)

# Display the first few rows to verify successful ingestion
df.head()

Loading dataset...

,dt,loc,lat,long,so2,no2,co,o3,pm10,pm2.5
0,1988010100,103,37.540037,127.002661,NaN,0.007,10.3,0.000,NaN,NaN
1,1988010100,105,37.593730,126.947561,0.340,0.055,12.6,0.043,NaN,NaN
2,1988010100,107,37.542043,127.047497,0.399,0.046,13.4,NaN,NaN,NaN
3,1988010100,108,37.547185,127.090304,0.261,0.034,5.4,0.000,NaN,NaN
4,1988010100,113,37.654140,127.026801,0.443,0.039,14.6,0.000,NaN,NaN

In [2]:
# Extract the subset for the target year (e.g., 2021)
target_year = '2021'

# Safely convert to string and check if it STARTS WITH the target year
print(f"Filtering data strictly for the year {target_year}...")
df_year = df[df['dt'].astype(str).str.startswith(target_year)]

# Verify the size reduction
print(f"Original dataset rows: {len(df)}")
print(f"Filtered dataset rows: {len(df_year)}")

# Save the subset to a new CSV file
output_path = f"data/seoul_{target_year}_sample.csv"
df_year.to_csv(output_path, index=False)

#Dsiplay the first few rows of the filtered dataset
df_year.head()

Filtering data strictly for the year 2021...
Original dataset rows: 5984782
Filtered dataset rows: 213414

,dt,loc,lat,long,so2,no2,co,o3,pm10,pm2.5
5771368,2021010100,101,37.572021,127.002819,NaN,0.016,0.5,0.022,24.0,14.0
5771369,2021010100,102,37.564302,126.972863,0.003,0.018,0.4,0.020,27.0,14.0
5771370,2021010100,103,37.540037,127.002661,0.003,0.018,0.4,0.015,37.0,12.0
5771371,2021010100,104,37.610084,126.932767,0.004,0.016,0.5,0.022,24.0,12.0
5771372,2021010100,105,37.593730,126.947561,0.005,0.023,0.8,0.015,18.0,15.0

In [3]:
# Inspect the newly created 1-year DataFrame
print("DataFrame Shape (Rows, Columns):", df_year.shape)

# Check data types and detect missing values (Nulls)
print("\nData Types and Missing Values Info")
df_year.info()

# Display the first rows to visually confirm the subset
df_year.head()

DataFrame Shape (Rows, Columns): (213414, 10)

Data Types and Missing Values Info
<class 'pandas.core.frame.DataFrame'>
Index: 213414 entries, 5771368 to 5984781
Data columns (total 10 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   dt      213414 non-null  int64
 1   loc     213414 non-null  int64
 2   lat     213414 non-null  float64
 3   long    213414 non-null  float64
 4   so2     212922 non-null  float64
 5   no2     212870 non-null  float64
 6   co      212949 non-null  float64
 7   o3      212966 non-null  float64
 8   pm10    210804 non-null  float64
 9   pm2.5   211766 non-null  float64
dtypes: float64(8), int64(2)
memory usage: 17.9 MB

,dt,loc,lat,long,so2,no2,co,o3,pm10,pm2.5
5771368,2021010100,101,37.572021,127.002819,NaN,0.016,0.5,0.022,24.0,14.0
5771369,2021010100,102,37.564302,126.972863,0.003,0.018,0.4,0.020,27.0,14.0
5771370,2021010100,103,37.540037,127.002661,0.003,0.018,0.4,0.015,37.0,12.0
5771371,2021010100,104,37.610084,126.932767,0.004,0.016,0.5,0.022,24.0,12.0
5771372,2021010100,105,37.593730,126.947561,0.005,0.023,0.8,0.015,18.0,15.0

In [6]:
# Remove rows with missing data
df_clean = df_year.dropna()

y = df_clean['pm2.5']
X = df_clean.drop(columns=['pm2.5'])

# Select the most important pollutants
selected_features = ['so2', 'no2', 'co', 'o3', 'pm10']
X_selected = X[selected_features]

# Scale the numbers to be on the same range
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_selected)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

print(f"Training features (X_train): {X_train.shape}")
print(f"Testing features (X_test): {X_test.shape}")

Training features (X_train): (167023, 5)
Testing features (X_test): (41756, 5)